ci:
  autoupdate_schedule: quarterly

default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.0"
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter, toml]
      - id: ruff-format # formatter
        types_or: [python, pyi, jupyter, toml]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        # MD013: line length
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        args: [--disable, MD013, MD033, MD041, MD024 "--"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        args: [--ignore-words-list, "statics,socio-economic,precessing,astroid", --check-filenames, --skip, "*.ipynb"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args: [-formatter, retain_line_breaks=true]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: text-unicode-replacement-char
        # Forbid files which have a UTF-8 Unicode replacement character.
  - repo: local
    hooks:
      - id: no-bracket-links
        name: "Brackets should not be inside links [[link]](url) -> [[link](url)]"
        entry: '\]\]\('
        language: pygrep
        types: [markdown]

      - id: no-http
        name: URLs must use HTTPS
        entry: "http:"
        language: pygrep
        types_or: [markdown, yaml]
        exclude: .pre-commit-config.yaml
